###
# Copyright (c) 2019-2020 Micro Focus or one of its affiliates.
#
# Licensed under the MIT License (the "License"); you may not use this file
# except in compliance with the License.
#
# The only warranties for products and services of Micro Focus and its affiliates
# and licensors ("Micro Focus") are as may be set forth in the express warranty
# statements accompanying such products and services. Nothing herein should be
# construed as constituting an additional warranty. Micro Focus shall not be
# liable for technical or editorial errors or omissions contained herein. The
# information contained herein is subject to change without notice.
###

# Basic IDOL container setup
# Uses nifi to ingest and index data into content
# Uses find to make search results available
# Default admin user is created for find in the community service
#  - see community/run_community.sh for details

version: "3.7"

# Change the IP to the address of an external IDOL LicenseServer instance
x-external-licenseserver-host: &external-licenseserver-host
  - idol-licenseserver:${LICENSESERVER_IP}

# Any files dropped into this volume will be ingested and indexed
volumes:
  idol-ingest-volume:

services:
  idol-content:
    image: ${IDOL_REGISTRY}/content:${IDOL_SERVER_VERSION}
    extra_hosts: *external-licenseserver-host
  idol-agentstore:
    image: ${IDOL_REGISTRY}/agentstore:${IDOL_SERVER_VERSION}
    extra_hosts: *external-licenseserver-host
  idol-categorisation-agentstore:
    image: ${IDOL_REGISTRY}/categorisation-agentstore:${IDOL_SERVER_VERSION}
    extra_hosts: *external-licenseserver-host
  idol-community:
    image: ${IDOL_REGISTRY}/community:${IDOL_SERVER_VERSION}
    extra_hosts: *external-licenseserver-host
    depends_on:
      - idol-content
      - idol-agentstore
  idol-view:
    image: ${IDOL_REGISTRY}/view:${IDOL_SERVER_VERSION}
    extra_hosts: *external-licenseserver-host
    depends_on:
      - idol-agentstore
  idol-nifi:
    image: ${IDOL_REGISTRY}/nifi-minimal:${IDOL_SERVER_VERSION} # choose nifi-minimal or nifi-full
    environment:
      - NIFI_WEB_PROXY_CONTEXT_PATH=/idol-nifi
      - NIFI_WEB_HTTP_PORT=8081
    extra_hosts: *external-licenseserver-host
    volumes:
      - idol-ingest-volume:/idol-ingest
      - ./nifi/flow/basic.xml:/opt/nifi/flow/this_flow.xml:ro # this controls which NiFi flow is used
  idol-find:
    image: ${IDOL_REGISTRY}/find:${IDOL_SERVER_VERSION}
    environment:
      - IDOL_UI_CFG=config_basic.json # this controls the configuration of Find
    depends_on:
      - idol-community
      - idol-view
  httpd-reverse-proxy:
    image: httpd:2.4
    volumes:
      - ./httpd-reverse-proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - idol-find
      - idol-nifi
    ports:
      - 8080:8080
